development:
  adapter: postgresql
  encoding: unicode
  database: rockr_development
  pool: 5
  host: localhost
  username: nickyhughes
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rockr_test
  pool: 5
  host: localhost
  username: nickyhughes
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rockr_production
  pool: 5
  host: localhost
  username: nickyhughes
  password:
